apiVersion: v1
data:
  mapRoles: |
    - groups:
      system:masters
      rolearn: arn:aws:iam::359260135968:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::359260135968:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-NNQWJ92A09NQ
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-04T05:09:33Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1296"
  uid: ce7e2088-d032-4ff6-b7f8-2b8542a56365
